#(无) = 重要消息；
#STATUS = 非重要消息；
#WARNING = CMake 警告, 会继续执行；
#AUTHOR_WARNING = CMake 警告 (dev), 会继续执行；
#SEND_ERROR = CMake 错误, 继续执行，但是会跳过生成的步骤；
#FATAL_ERROR = CMake 错误, 终止所有处理过程；
message(STATUS "=====VAR-BEGIN===============================")

message(STATUS "CMAKE_HOST_SYSTEM_NAME = " ${CMAKE_HOST_SYSTEM_NAME})
message(STATUS "CMAKE_HOST_SYSTEM_PROCESSOR = " ${CMAKE_HOST_SYSTEM_PROCESSOR})
message(STATUS "CMAKE_HOST_UNIX = " ${CMAKE_HOST_UNIX})
message(STATUS "CMAKE_HOST_WIN32 = " ${CMAKE_HOST_WIN32})
message(STATUS "UNIX = " ${UNIX})
message(STATUS "WIN32 = " ${WIN32})

message(STATUS "CMAKE_SYSTEM_NAME = " ${CMAKE_SYSTEM_NAME})
message(STATUS "CMAKE_SYSTEM_PROCESSOR = " ${CMAKE_SYSTEM_PROCESSOR})
message(STATUS "CMAKE_SYSTEM_VERSION = " ${CMAKE_SYSTEM_VERSION})
message(STATUS "CMAKE_SYSTEM_INCLUDE_PATH = " ${CMAKE_SYSTEM_INCLUDE_PATH})
message(STATUS "CMAKE_SYSTEM_LIBRARY_PATH = " ${CMAKE_SYSTEM_LIBRARY_PATH})

message(STATUS "CMAKE_PREFIX_PATH = " ${CMAKE_PREFIX_PATH})
message(STATUS "CMAKE_BINARY_DIR = " ${CMAKE_BINARY_DIR})
message(STATUS "CMAKE_MAKE_PROGRAM = " ${CMAKE_MAKE_PROGRAM})
message(STATUS "CMAKE_CONFIGURATION_TYPES = " ${CMAKE_CONFIGURATION_TYPES})
message(STATUS "CMAKE_BUILD_TYPE = " ${CMAKE_BUILD_TYPE})
message(STATUS "CMAKE_BUILD_TOOL = " ${CMAKE_BUILD_TOOL})
message(STATUS "CMAKE_EXECUTABLE_SUFFIX_C = " ${CMAKE_EXECUTABLE_SUFFIX_C})
message(STATUS "CMAKE_EXECUTABLE_SUFFIX_CXX = " ${CMAKE_EXECUTABLE_SUFFIX_CXX})
message(STATUS "CMAKE_MSVC_RUNTIME_LIBRARY = " ${CMAKE_MSVC_RUNTIME_LIBRARY})
message(STATUS "CMAKE_AUTOGEN_PARALLEL = " ${CMAKE_AUTOGEN_PARALLEL})
message(STATUS "CMAKE_BUILD_PARALLEL_LEVEL = " ${CMAKE_BUILD_PARALLEL_LEVEL})

message(STATUS "BUILD_SHARED_LIBS = " ${BUILD_SHARED_LIBS})
message(STATUS "CMAKE_TOOLCHAIN_FILE = " ${CMAKE_TOOLCHAIN_FILE})
message(STATUS "CMAKE_CROSS_CONFIGS = " ${CMAKE_CROSS_CONFIGS})
message(STATUS "CMAKE_CROSSCOMPILING = " ${CMAKE_CROSSCOMPILING})
message(STATUS "CMAKE_CROSSCOMPILING_EMULATOR = " ${CMAKE_CROSSCOMPILING_EMULATOR})

message(STATUS "PROJECT_NAME = " ${PROJECT_NAME})
message(STATUS "PROJECT_VERSION = " ${PROJECT_VERSION})
message(STATUS "CMAKE_SOURCE_DIR = " ${CMAKE_SOURCE_DIR})
message(STATUS "PROJECT_SOURCE_DIR = " ${PROJECT_SOURCE_DIR})
message(STATUS "CMAKE_CURRENT_SOURCE_DIR = " ${CMAKE_CURRENT_SOURCE_DIR})
message(STATUS "CMAKE_INCLUDE_CURRENT_DIR = " ${CMAKE_INCLUDE_CURRENT_DIR})

message(STATUS "CMAKE_SYSROOT = " ${CMAKE_SYSROOT})
message(STATUS "CMAKE_SYSROOT_COMPILE = " ${CMAKE_SYSROOT_COMPILE})
message(STATUS "CMAKE_SYSROOT_LINK = " ${CMAKE_SYSROOT_LINK})

message(STATUS "CMAKE_STAGING_PREFIX  = " ${CMAKE_STAGING_PREFIX})
message(STATUS "CMAKE_INSTALL_PREFIX = " ${CMAKE_INSTALL_PREFIX})

message(STATUS "CMAKE_BUILD_WITH_INSTALL_RPATH = " ${CMAKE_BUILD_WITH_INSTALL_RPATH})
message(STATUS "CMAKE_INSTALL_RPATH = " ${CMAKE_INSTALL_RPATH})

message(STATUS "CMAKE_ANDROID_STANDALONE_TOOLCHAIN = " ${CMAKE_ANDROID_STANDALONE_TOOLCHAIN})
message(STATUS "CMAKE_ANDROID_NDK = " ${CMAKE_ANDROID_NDK})
message(STATUS "CMAKE_ANDROID_API = " ${CMAKE_ANDROID_API})
message(STATUS "CMAKE_ANDROID_ARCH_ABI = " ${CMAKE_ANDROID_ARCH_ABI})
message(STATUS "CMAKE_ANDROID_STL_TYPE = " ${CMAKE_ANDROID_STL_TYPE})
message(STATUS "CMAKE_ANDROID_ARM_MODE = " ${CMAKE_ANDROID_ARM_MODE})
message(STATUS "CMAKE_ANDROID_ARM_NEON = " ${CMAKE_ANDROID_ARM_NEON})
message(STATUS "CMAKE_ANDROID_RTTI = " ${CMAKE_ANDROID_RTTI})
message(STATUS "CMAKE_ANDROID_EXCEPTIONS = " ${CMAKE_ANDROID_EXCEPTIONS})

message(STATUS "CMAKE_FIND_ROOT_PATH = " ${CMAKE_FIND_ROOT_PATH})
message(STATUS "CMAKE_FIND_ROOT_PATH_MODE_PROGRAM = " ${CMAKE_FIND_ROOT_PATH_MODE_PROGRAM})
message(STATUS "CMAKE_FIND_ROOT_PATH_MODE_LIBRARY = " ${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
message(STATUS "CMAKE_FIND_ROOT_PATH_MODE_INCLUDE = " ${CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
message(STATUS "CMAKE_FIND_ROOT_PATH_MODE_PACKAGE = " ${CMAKE_FIND_ROOT_PATH_MODE_PACKAGE})

message(STATUS "CMAKE_AR = " ${CMAKE_AR})
message(STATUS "CMAKE_LINKER = " ${CMAKE_LINKER})
message(STATUS "CMAKE_NM = " ${CMAKE_NM})
message(STATUS "CMAKE_OBJDUMP = " ${CMAKE_OBJDUMP})
message(STATUS "CMAKE_RANLIB = " ${CMAKE_RANLIB})
message(STATUS "CMAKE_RC_COMPILER = " ${CMAKE_RC_COMPILER})

message(STATUS "CMAKE_C_COMPILER_ID = " ${CMAKE_C_COMPILER_ID})
message(STATUS "CMAKE_CXX_COMPILER_ID = " ${CMAKE_CXX_COMPILER_ID})

message(STATUS "CMAKE_C_COMPILER = " ${CMAKE_C_COMPILER})
message(STATUS "CMAKE_CXX_COMPILER = " ${CMAKE_CXX_COMPILER})

message(STATUS "CMAKE_C_COMPILER_VERSION = " ${CMAKE_C_COMPILER_VERSION})
message(STATUS "CMAKE_CXX_COMPILER_VERSION = " ${CMAKE_CXX_COMPILER_VERSION})

message(STATUS "CMAKE_C_COMPILER_TARGET = " ${CMAKE_C_COMPILER_TARGET})
message(STATUS "CMAKE_CXX_COMPILER_TARGET = " ${CMAKE_CXX_COMPILER_TARGET})
 
message(STATUS "CMAKE_RC_FLAGS = " ${CMAKE_RC_FLAGS})
message(STATUS "CMAKE_RC_FLAGS_DEBUG = " ${CMAKE_RC_FLAGS_DEBUG})
message(STATUS "CMAKE_RC_FLAGS_RELEASE = " ${CMAKE_RC_FLAGS_RELEASE})
message(STATUS "CMAKE_RC_FLAGS_RELWITHDEBINFO = " ${CMAKE_RC_FLAGS_RELWITHDEBINFO})

message(STATUS "CMAKE_C_FLAGS = " ${CMAKE_C_FLAGS})
message(STATUS "CMAKE_C_STANDARD = " ${CMAKE_C_STANDARD})
message(STATUS "CMAKE_C_FLAGS_DEBUG = " ${CMAKE_C_FLAGS_DEBUG})
message(STATUS "CMAKE_C_FLAGS_RELEASE = " ${CMAKE_C_FLAGS_RELEASE})
message(STATUS "CMAKE_C_FLAGS_RELWITHDEBINFO = " ${CMAKE_C_FLAGS_RELWITHDEBINFO})

message(STATUS "CMAKE_CXX_FLAGS = " ${CMAKE_CXX_FLAGS})
message(STATUS "CMAKE_CXX_STANDARD = " ${CMAKE_CXX_STANDARD})
message(STATUS "CMAKE_CXX_FLAGS_DEBUG = " ${CMAKE_CXX_FLAGS_DEBUG})
message(STATUS "CMAKE_CXX_FLAGS_RELEASE = " ${CMAKE_CXX_FLAGS_RELEASE})
message(STATUS "CMAKE_CXX_FLAGS_RELWITHDEBINFO = " ${CMAKE_CXX_FLAGS_RELWITHDEBINFO})

message(STATUS "CMAKE_EXE_LINKER_FLAGS = " ${CMAKE_EXE_LINKER_FLAGS})
message(STATUS "CMAKE_EXE_LINKER_FLAGS_DEBUG = " ${CMAKE_EXE_LINKER_FLAGS_DEBUG})
message(STATUS "CMAKE_EXE_LINKER_FLAGS_RELEASE = " ${CMAKE_EXE_LINKER_FLAGS_RELEASE})
message(STATUS "CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO = " ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO})

message(STATUS "CMAKE_MODULE_LINKER_FLAGS = " ${CMAKE_MODULE_LINKER_FLAGS})
message(STATUS "CMAKE_MODULE_LINKER_FLAGS_DEBUG = " ${CMAKE_MODULE_LINKER_FLAGS_DEBUG})
message(STATUS "CMAKE_MODULE_LINKER_FLAGS_RELEASE = " ${CMAKE_MODULE_LINKER_FLAGS_RELEASE})
message(STATUS "CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO = " ${CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO})

message(STATUS "CMAKE_SHARED_LINKER_FLAGS = " ${CMAKE_SHARED_LINKER_FLAGS})
message(STATUS "CMAKE_SHARED_LINKER_FLAGS_DEBUG = " ${CMAKE_SHARED_LINKER_FLAGS_DEBUG})
message(STATUS "CMAKE_SHARED_LINKER_FLAGS_RELEASE = " ${CMAKE_SHARED_LINKER_FLAGS_RELEASE})
message(STATUS "CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO = " ${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO})

message(STATUS "CMAKE_STATIC_LINKER_FLAGS = " ${CMAKE_STATIC_LINKER_FLAGS})
message(STATUS "CMAKE_STATIC_LINKER_FLAGS_DEBUG = " ${CMAKE_STATIC_LINKER_FLAGS_DEBUG})
message(STATUS "CMAKE_STATIC_LINKER_FLAGS_RELEASE = " ${CMAKE_STATIC_LINKER_FLAGS_RELEASE})
message(STATUS "CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO = " ${CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO})

message(STATUS "CMAKE_MSVC_RUNTIME_LIBRARY = " ${CMAKE_MSVC_RUNTIME_LIBRARY})

message(STATUS "=====VAR-END===============================")

