set(CMAKE_SYSROOT $ENV{TOOLCHAIN_HOME}/x86_64-debian10-linux-gnu)
set(GCC_TOOLCHAIN_DIR $ENV{TOOLCHAIN_HOME}/x86_64-debian10-linux-gnu/usr)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CLANG_TARGET x86_64-pc-linux-gnu)

set(CMAKE_THREAD_LIBS_INIT -lpthread)
set(CMAKE_HAVE_THREADS_LIBRARY ON)
set(CMAKE_USE_WIN32_THREADS_INIT OFF)
set(CMAKE_USE_PTHREADS_INIT ON)
set(THREADS_PREFER_PTHREAD_FLAG ON)

include($ENV{TOOLCHAIN_HOME}/cmake/clang.toolchain.cmake)

